### ISSUE TITLE
Non-GPU support available?

### ISSUE THREAD

**Issue by DennisDavari** [liamcripwell/sle#1]
When I want to run the metric I get the following error message: "AssertionError: Torch not compiled with CUDA enabled". When setting up the metric on a Google Colab GPU machine it works without any problems. Is it possible to use the metric without having an NVIDIA graphics card? 

Thanks in advance!

**Comment by liamcripwell** [comment]
Hi Dennis,

You can specify a target device in the scorer initializer. If you set it to "cpu" it should work.

```python
scorer = SLEScorer("liamcripwell/sle-base", device="cpu")
```

**Comment by DennisDavari** [comment]
Thank you very much! That works for me.
